// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: container/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EpicChainAPI.v2.Container {

  /// <summary>Holder for reflection information generated from container/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for container/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdjb250YWluZXIvc2VydmljZS5wcm90bxITbmVvLmZzLnYyLmNvbnRhaW5l",
            "choPYWNsL3R5cGVzLnByb3RvGhVjb250YWluZXIvdHlwZXMucHJvdG8aEHJl",
            "ZnMvdHlwZXMucHJvdG8aE3Nlc3Npb24vdHlwZXMucHJvdG8iqQIKClB1dFJl",
            "cXVlc3QSMgoEYm9keRgBIAEoCzIkLm5lby5mcy52Mi5jb250YWluZXIuUHV0",
            "UmVxdWVzdC5Cb2R5EjkKC21ldGFfaGVhZGVyGAIgASgLMiQubmVvLmZzLnYy",
            "LnNlc3Npb24uUmVxdWVzdE1ldGFIZWFkZXISQwoNdmVyaWZ5X2hlYWRlchgD",
            "IAEoCzIsLm5lby5mcy52Mi5zZXNzaW9uLlJlcXVlc3RWZXJpZmljYXRpb25I",
            "ZWFkZXIaZwoEQm9keRIxCgljb250YWluZXIYASABKAsyHi5uZW8uZnMudjIu",
            "Y29udGFpbmVyLkNvbnRhaW5lchIsCglzaWduYXR1cmUYAiABKAsyGS5uZW8u",
            "ZnMudjIucmVmcy5TaWduYXR1cmUi/wEKC1B1dFJlc3BvbnNlEjMKBGJvZHkY",
            "ASABKAsyJS5uZW8uZnMudjIuY29udGFpbmVyLlB1dFJlc3BvbnNlLkJvZHkS",
            "OgoLbWV0YV9oZWFkZXIYAiABKAsyJS5uZW8uZnMudjIuc2Vzc2lvbi5SZXNw",
            "b25zZU1ldGFIZWFkZXISRAoNdmVyaWZ5X2hlYWRlchgDIAEoCzItLm5lby5m",
            "cy52Mi5zZXNzaW9uLlJlc3BvbnNlVmVyaWZpY2F0aW9uSGVhZGVyGjkKBEJv",
            "ZHkSMQoMY29udGFpbmVyX2lkGAEgASgLMhsubmVvLmZzLnYyLnJlZnMuQ29u",
            "dGFpbmVySUQirwIKDURlbGV0ZVJlcXVlc3QSNQoEYm9keRgBIAEoCzInLm5l",
            "by5mcy52Mi5jb250YWluZXIuRGVsZXRlUmVxdWVzdC5Cb2R5EjkKC21ldGFf",
            "aGVhZGVyGAIgASgLMiQubmVvLmZzLnYyLnNlc3Npb24uUmVxdWVzdE1ldGFI",
            "ZWFkZXISQwoNdmVyaWZ5X2hlYWRlchgDIAEoCzIsLm5lby5mcy52Mi5zZXNz",
            "aW9uLlJlcXVlc3RWZXJpZmljYXRpb25IZWFkZXIaZwoEQm9keRIxCgxjb250",
            "YWluZXJfaWQYASABKAsyGy5uZW8uZnMudjIucmVmcy5Db250YWluZXJJRBIs",
            "CglzaWduYXR1cmUYAiABKAsyGS5uZW8uZnMudjIucmVmcy5TaWduYXR1cmUi",
            "0gEKDkRlbGV0ZVJlc3BvbnNlEjYKBGJvZHkYASABKAsyKC5uZW8uZnMudjIu",
            "Y29udGFpbmVyLkRlbGV0ZVJlc3BvbnNlLkJvZHkSOgoLbWV0YV9oZWFkZXIY",
            "AiABKAsyJS5uZW8uZnMudjIuc2Vzc2lvbi5SZXNwb25zZU1ldGFIZWFkZXIS",
            "RAoNdmVyaWZ5X2hlYWRlchgDIAEoCzItLm5lby5mcy52Mi5zZXNzaW9uLlJl",
            "c3BvbnNlVmVyaWZpY2F0aW9uSGVhZGVyGgYKBEJvZHki+wEKCkdldFJlcXVl",
            "c3QSMgoEYm9keRgBIAEoCzIkLm5lby5mcy52Mi5jb250YWluZXIuR2V0UmVx",
            "dWVzdC5Cb2R5EjkKC21ldGFfaGVhZGVyGAIgASgLMiQubmVvLmZzLnYyLnNl",
            "c3Npb24uUmVxdWVzdE1ldGFIZWFkZXISQwoNdmVyaWZ5X2hlYWRlchgDIAEo",
            "CzIsLm5lby5mcy52Mi5zZXNzaW9uLlJlcXVlc3RWZXJpZmljYXRpb25IZWFk",
            "ZXIaOQoEQm9keRIxCgxjb250YWluZXJfaWQYASABKAsyGy5uZW8uZnMudjIu",
            "cmVmcy5Db250YWluZXJJRCL/AQoLR2V0UmVzcG9uc2USMwoEYm9keRgBIAEo",
            "CzIlLm5lby5mcy52Mi5jb250YWluZXIuR2V0UmVzcG9uc2UuQm9keRI6Cgtt",
            "ZXRhX2hlYWRlchgCIAEoCzIlLm5lby5mcy52Mi5zZXNzaW9uLlJlc3BvbnNl",
            "TWV0YUhlYWRlchJECg12ZXJpZnlfaGVhZGVyGAMgASgLMi0ubmVvLmZzLnYy",
            "LnNlc3Npb24uUmVzcG9uc2VWZXJpZmljYXRpb25IZWFkZXIaOQoEQm9keRIx",
            "Cgljb250YWluZXIYASABKAsyHi5uZW8uZnMudjIuY29udGFpbmVyLkNvbnRh",
            "aW5lciL1AQoLTGlzdFJlcXVlc3QSMwoEYm9keRgBIAEoCzIlLm5lby5mcy52",
            "Mi5jb250YWluZXIuTGlzdFJlcXVlc3QuQm9keRI5CgttZXRhX2hlYWRlchgC",
            "IAEoCzIkLm5lby5mcy52Mi5zZXNzaW9uLlJlcXVlc3RNZXRhSGVhZGVyEkMK",
            "DXZlcmlmeV9oZWFkZXIYAyABKAsyLC5uZW8uZnMudjIuc2Vzc2lvbi5SZXF1",
            "ZXN0VmVyaWZpY2F0aW9uSGVhZGVyGjEKBEJvZHkSKQoIb3duZXJfaWQYASAB",
            "KAsyFy5uZW8uZnMudjIucmVmcy5Pd25lcklEIoICCgxMaXN0UmVzcG9uc2US",
            "NAoEYm9keRgBIAEoCzImLm5lby5mcy52Mi5jb250YWluZXIuTGlzdFJlc3Bv",
            "bnNlLkJvZHkSOgoLbWV0YV9oZWFkZXIYAiABKAsyJS5uZW8uZnMudjIuc2Vz",
            "c2lvbi5SZXNwb25zZU1ldGFIZWFkZXISRAoNdmVyaWZ5X2hlYWRlchgDIAEo",
            "CzItLm5lby5mcy52Mi5zZXNzaW9uLlJlc3BvbnNlVmVyaWZpY2F0aW9uSGVh",
            "ZGVyGjoKBEJvZHkSMgoNY29udGFpbmVyX2lkcxgBIAMoCzIbLm5lby5mcy52",
            "Mi5yZWZzLkNvbnRhaW5lcklEIrQCChVTZXRFeHRlbmRlZEFDTFJlcXVlc3QS",
            "PQoEYm9keRgBIAEoCzIvLm5lby5mcy52Mi5jb250YWluZXIuU2V0RXh0ZW5k",
            "ZWRBQ0xSZXF1ZXN0LkJvZHkSOQoLbWV0YV9oZWFkZXIYAiABKAsyJC5uZW8u",
            "ZnMudjIuc2Vzc2lvbi5SZXF1ZXN0TWV0YUhlYWRlchJDCg12ZXJpZnlfaGVh",
            "ZGVyGAMgASgLMiwubmVvLmZzLnYyLnNlc3Npb24uUmVxdWVzdFZlcmlmaWNh",
            "dGlvbkhlYWRlchpcCgRCb2R5EiYKBGVhY2wYASABKAsyGC5uZW8uZnMudjIu",
            "YWNsLkVBQ0xUYWJsZRIsCglzaWduYXR1cmUYAiABKAsyGS5uZW8uZnMudjIu",
            "cmVmcy5TaWduYXR1cmUi4gEKFlNldEV4dGVuZGVkQUNMUmVzcG9uc2USPgoE",
            "Ym9keRgBIAEoCzIwLm5lby5mcy52Mi5jb250YWluZXIuU2V0RXh0ZW5kZWRB",
            "Q0xSZXNwb25zZS5Cb2R5EjoKC21ldGFfaGVhZGVyGAIgASgLMiUubmVvLmZz",
            "LnYyLnNlc3Npb24uUmVzcG9uc2VNZXRhSGVhZGVyEkQKDXZlcmlmeV9oZWFk",
            "ZXIYAyABKAsyLS5uZW8uZnMudjIuc2Vzc2lvbi5SZXNwb25zZVZlcmlmaWNh",
            "dGlvbkhlYWRlchoGCgRCb2R5IpECChVHZXRFeHRlbmRlZEFDTFJlcXVlc3QS",
            "PQoEYm9keRgBIAEoCzIvLm5lby5mcy52Mi5jb250YWluZXIuR2V0RXh0ZW5k",
            "ZWRBQ0xSZXF1ZXN0LkJvZHkSOQoLbWV0YV9oZWFkZXIYAiABKAsyJC5uZW8u",
            "ZnMudjIuc2Vzc2lvbi5SZXF1ZXN0TWV0YUhlYWRlchJDCg12ZXJpZnlfaGVh",
            "ZGVyGAMgASgLMiwubmVvLmZzLnYyLnNlc3Npb24uUmVxdWVzdFZlcmlmaWNh",
            "dGlvbkhlYWRlcho5CgRCb2R5EjEKDGNvbnRhaW5lcl9pZBgBIAEoCzIbLm5l",
            "by5mcy52Mi5yZWZzLkNvbnRhaW5lcklEIrgCChZHZXRFeHRlbmRlZEFDTFJl",
            "c3BvbnNlEj4KBGJvZHkYASABKAsyMC5uZW8uZnMudjIuY29udGFpbmVyLkdl",
            "dEV4dGVuZGVkQUNMUmVzcG9uc2UuQm9keRI6CgttZXRhX2hlYWRlchgCIAEo",
            "CzIlLm5lby5mcy52Mi5zZXNzaW9uLlJlc3BvbnNlTWV0YUhlYWRlchJECg12",
            "ZXJpZnlfaGVhZGVyGAMgASgLMi0ubmVvLmZzLnYyLnNlc3Npb24uUmVzcG9u",
            "c2VWZXJpZmljYXRpb25IZWFkZXIaXAoEQm9keRImCgRlYWNsGAEgASgLMhgu",
            "bmVvLmZzLnYyLmFjbC5FQUNMVGFibGUSLAoJc2lnbmF0dXJlGAIgASgLMhku",
            "bmVvLmZzLnYyLnJlZnMuU2lnbmF0dXJlIqMDChhBbm5vdW5jZVVzZWRTcGFj",
            "ZVJlcXVlc3QSQAoEYm9keRgBIAEoCzIyLm5lby5mcy52Mi5jb250YWluZXIu",
            "QW5ub3VuY2VVc2VkU3BhY2VSZXF1ZXN0LkJvZHkSOQoLbWV0YV9oZWFkZXIY",
            "AiABKAsyJC5uZW8uZnMudjIuc2Vzc2lvbi5SZXF1ZXN0TWV0YUhlYWRlchJD",
            "Cg12ZXJpZnlfaGVhZGVyGAMgASgLMiwubmVvLmZzLnYyLnNlc3Npb24uUmVx",
            "dWVzdFZlcmlmaWNhdGlvbkhlYWRlchrEAQoEQm9keRJWCg1hbm5vdW5jZW1l",
            "bnRzGAEgAygLMj8ubmVvLmZzLnYyLmNvbnRhaW5lci5Bbm5vdW5jZVVzZWRT",
            "cGFjZVJlcXVlc3QuQm9keS5Bbm5vdW5jZW1lbnQaZAoMQW5ub3VuY2VtZW50",
            "Eg0KBWVwb2NoGAEgASgEEjEKDGNvbnRhaW5lcl9pZBgCIAEoCzIbLm5lby5m",
            "cy52Mi5yZWZzLkNvbnRhaW5lcklEEhIKCnVzZWRfc3BhY2UYAyABKAQi6AEK",
            "GUFubm91bmNlVXNlZFNwYWNlUmVzcG9uc2USQQoEYm9keRgBIAEoCzIzLm5l",
            "by5mcy52Mi5jb250YWluZXIuQW5ub3VuY2VVc2VkU3BhY2VSZXNwb25zZS5C",
            "b2R5EjoKC21ldGFfaGVhZGVyGAIgASgLMiUubmVvLmZzLnYyLnNlc3Npb24u",
            "UmVzcG9uc2VNZXRhSGVhZGVyEkQKDXZlcmlmeV9oZWFkZXIYAyABKAsyLS5u",
            "ZW8uZnMudjIuc2Vzc2lvbi5SZXNwb25zZVZlcmlmaWNhdGlvbkhlYWRlchoG",
            "CgRCb2R5MpAFChBDb250YWluZXJTZXJ2aWNlEkgKA1B1dBIfLm5lby5mcy52",
            "Mi5jb250YWluZXIuUHV0UmVxdWVzdBogLm5lby5mcy52Mi5jb250YWluZXIu",
            "UHV0UmVzcG9uc2USUQoGRGVsZXRlEiIubmVvLmZzLnYyLmNvbnRhaW5lci5E",
            "ZWxldGVSZXF1ZXN0GiMubmVvLmZzLnYyLmNvbnRhaW5lci5EZWxldGVSZXNw",
            "b25zZRJICgNHZXQSHy5uZW8uZnMudjIuY29udGFpbmVyLkdldFJlcXVlc3Qa",
            "IC5uZW8uZnMudjIuY29udGFpbmVyLkdldFJlc3BvbnNlEksKBExpc3QSIC5u",
            "ZW8uZnMudjIuY29udGFpbmVyLkxpc3RSZXF1ZXN0GiEubmVvLmZzLnYyLmNv",
            "bnRhaW5lci5MaXN0UmVzcG9uc2USaQoOU2V0RXh0ZW5kZWRBQ0wSKi5uZW8u",
            "ZnMudjIuY29udGFpbmVyLlNldEV4dGVuZGVkQUNMUmVxdWVzdBorLm5lby5m",
            "cy52Mi5jb250YWluZXIuU2V0RXh0ZW5kZWRBQ0xSZXNwb25zZRJpCg5HZXRF",
            "eHRlbmRlZEFDTBIqLm5lby5mcy52Mi5jb250YWluZXIuR2V0RXh0ZW5kZWRB",
            "Q0xSZXF1ZXN0GisubmVvLmZzLnYyLmNvbnRhaW5lci5HZXRFeHRlbmRlZEFD",
            "TFJlc3BvbnNlEnIKEUFubm91bmNlVXNlZFNwYWNlEi0ubmVvLmZzLnYyLmNv",
            "bnRhaW5lci5Bbm5vdW5jZVVzZWRTcGFjZVJlcXVlc3QaLi5uZW8uZnMudjIu",
            "Y29udGFpbmVyLkFubm91bmNlVXNlZFNwYWNlUmVzcG9uc2VCWFo9Z2l0aHVi",
            "LmNvbS9uc3BjYy1kZXYvbmVvZnMtYXBpLWdvL3YyL2NvbnRhaW5lci9ncnBj",
            "O2NvbnRhaW5lcqoCFk5lb0ZTLkFQSS52Mi5Db250YWluZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EpicChainAPI.v2.Acl.TypesReflection.Descriptor, global::EpicChainAPI.v2.Container.TypesReflection.Descriptor, global::EpicChainAPI.v2.Refs.TypesReflection.Descriptor, global::EpicChainAPI.v2.Session.TypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.PutRequest), global::EpicChainAPI.v2.Container.PutRequest.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.PutRequest.Types.Body), global::EpicChainAPI.v2.Container.PutRequest.Types.Body.Parser, new[]{ "Container", "Signature" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.PutResponse), global::EpicChainAPI.v2.Container.PutResponse.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.PutResponse.Types.Body), global::EpicChainAPI.v2.Container.PutResponse.Types.Body.Parser, new[]{ "ContainerId" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.DeleteRequest), global::EpicChainAPI.v2.Container.DeleteRequest.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.DeleteRequest.Types.Body), global::EpicChainAPI.v2.Container.DeleteRequest.Types.Body.Parser, new[]{ "ContainerId", "Signature" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.DeleteResponse), global::EpicChainAPI.v2.Container.DeleteResponse.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.DeleteResponse.Types.Body), global::EpicChainAPI.v2.Container.DeleteResponse.Types.Body.Parser, null, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetRequest), global::EpicChainAPI.v2.Container.GetRequest.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetRequest.Types.Body), global::EpicChainAPI.v2.Container.GetRequest.Types.Body.Parser, new[]{ "ContainerId" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetResponse), global::EpicChainAPI.v2.Container.GetResponse.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetResponse.Types.Body), global::EpicChainAPI.v2.Container.GetResponse.Types.Body.Parser, new[]{ "Container" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.ListRequest), global::EpicChainAPI.v2.Container.ListRequest.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.ListRequest.Types.Body), global::EpicChainAPI.v2.Container.ListRequest.Types.Body.Parser, new[]{ "OwnerId" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.ListResponse), global::EpicChainAPI.v2.Container.ListResponse.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.ListResponse.Types.Body), global::EpicChainAPI.v2.Container.ListResponse.Types.Body.Parser, new[]{ "ContainerIds" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.SetExtendedACLRequest), global::EpicChainAPI.v2.Container.SetExtendedACLRequest.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.SetExtendedACLRequest.Types.Body), global::EpicChainAPI.v2.Container.SetExtendedACLRequest.Types.Body.Parser, new[]{ "Eacl", "Signature" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.SetExtendedACLResponse), global::EpicChainAPI.v2.Container.SetExtendedACLResponse.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.SetExtendedACLResponse.Types.Body), global::EpicChainAPI.v2.Container.SetExtendedACLResponse.Types.Body.Parser, null, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetExtendedACLRequest), global::EpicChainAPI.v2.Container.GetExtendedACLRequest.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetExtendedACLRequest.Types.Body), global::EpicChainAPI.v2.Container.GetExtendedACLRequest.Types.Body.Parser, new[]{ "ContainerId" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetExtendedACLResponse), global::EpicChainAPI.v2.Container.GetExtendedACLResponse.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.GetExtendedACLResponse.Types.Body), global::EpicChainAPI.v2.Container.GetExtendedACLResponse.Types.Body.Parser, new[]{ "Eacl", "Signature" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.AnnounceUsedSpaceRequest), global::EpicChainAPI.v2.Container.AnnounceUsedSpaceRequest.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.AnnounceUsedSpaceRequest.Types.Body), global::EpicChainAPI.v2.Container.AnnounceUsedSpaceRequest.Types.Body.Parser, new[]{ "Announcements" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.AnnounceUsedSpaceRequest.Types.Body.Types.Announcement), global::EpicChainAPI.v2.Container.AnnounceUsedSpaceRequest.Types.Body.Types.Announcement.Parser, new[]{ "Epoch", "ContainerId", "UsedSpace" }, null, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.AnnounceUsedSpaceResponse), global::EpicChainAPI.v2.Container.AnnounceUsedSpaceResponse.Parser, new[]{ "Body", "MetaHeader", "VerifyHeader" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::EpicChainAPI.v2.Container.AnnounceUsedSpaceResponse.Types.Body), global::EpicChainAPI.v2.Container.AnnounceUsedSpaceResponse.Types.Body.Parser, null, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// New NeoFS Container creation request
  /// </summary>
  public sealed partial class PutRequest : pb::IMessage<PutRequest> {
    private static readonly pb::MessageParser<PutRequest> _parser = new pb::MessageParser<PutRequest>(() => new PutRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EpicChainAPI.v2.Container.ServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRequest(PutRequest other) : this() {
      body_ = other.body_ != null ? other.body_.Clone() : null;
      metaHeader_ = other.metaHeader_ != null ? other.metaHeader_.Clone() : null;
      verifyHeader_ = other.verifyHeader_ != null ? other.verifyHeader_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRequest Clone() {
      return new PutRequest(this);
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 1;
    private global::EpicChainAPI.v2.Container.PutRequest.Types.Body body_;
    /// <summary>
    /// Body of container put request message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Container.PutRequest.Types.Body Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    /// <summary>Field number for the "meta_header" field.</summary>
    public const int MetaHeaderFieldNumber = 2;
    private global::EpicChainAPI.v2.Session.RequestMetaHeader metaHeader_;
    /// <summary>
    /// Carries request meta information. Header data is used only to regulate
    /// message transport and does not affect request execution.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.RequestMetaHeader MetaHeader {
      get { return metaHeader_; }
      set {
        metaHeader_ = value;
      }
    }

    /// <summary>Field number for the "verify_header" field.</summary>
    public const int VerifyHeaderFieldNumber = 3;
    private global::EpicChainAPI.v2.Session.RequestVerificationHeader verifyHeader_;
    /// <summary>
    /// Carries request verification information. This header is used to
    /// authenticate the nodes of the message route and check the correctness of
    /// transmission.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.RequestVerificationHeader VerifyHeader {
      get { return verifyHeader_; }
      set {
        verifyHeader_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Body, other.Body)) return false;
      if (!object.Equals(MetaHeader, other.MetaHeader)) return false;
      if (!object.Equals(VerifyHeader, other.VerifyHeader)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (body_ != null) hash ^= Body.GetHashCode();
      if (metaHeader_ != null) hash ^= MetaHeader.GetHashCode();
      if (verifyHeader_ != null) hash ^= VerifyHeader.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (body_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Body);
      }
      if (metaHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MetaHeader);
      }
      if (verifyHeader_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VerifyHeader);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (metaHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MetaHeader);
      }
      if (verifyHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VerifyHeader);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutRequest other) {
      if (other == null) {
        return;
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::EpicChainAPI.v2.Container.PutRequest.Types.Body();
        }
        Body.MergeFrom(other.Body);
      }
      if (other.metaHeader_ != null) {
        if (metaHeader_ == null) {
          MetaHeader = new global::EpicChainAPI.v2.Session.RequestMetaHeader();
        }
        MetaHeader.MergeFrom(other.MetaHeader);
      }
      if (other.verifyHeader_ != null) {
        if (verifyHeader_ == null) {
          VerifyHeader = new global::EpicChainAPI.v2.Session.RequestVerificationHeader();
        }
        VerifyHeader.MergeFrom(other.VerifyHeader);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (body_ == null) {
              Body = new global::EpicChainAPI.v2.Container.PutRequest.Types.Body();
            }
            input.ReadMessage(Body);
            break;
          }
          case 18: {
            if (metaHeader_ == null) {
              MetaHeader = new global::EpicChainAPI.v2.Session.RequestMetaHeader();
            }
            input.ReadMessage(MetaHeader);
            break;
          }
          case 26: {
            if (verifyHeader_ == null) {
              VerifyHeader = new global::EpicChainAPI.v2.Session.RequestVerificationHeader();
            }
            input.ReadMessage(VerifyHeader);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PutRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Container creation request has container structure's signature as a
      /// separate field. It's not stored in sidechain, just verified on container
      /// creation by `Container` smart contract. `ContainerID` is a SHA256 hash of
      /// the stable-marshalled container strucutre, hence there is no need for
      /// additional signature checks.
      /// </summary>
      public sealed partial class Body : pb::IMessage<Body> {
        private static readonly pb::MessageParser<Body> _parser = new pb::MessageParser<Body>(() => new Body());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Body> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::EpicChainAPI.v2.Container.PutRequest.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body(Body other) : this() {
          container_ = other.container_ != null ? other.container_.Clone() : null;
          signature_ = other.signature_ != null ? other.signature_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body Clone() {
          return new Body(this);
        }

        /// <summary>Field number for the "container" field.</summary>
        public const int ContainerFieldNumber = 1;
        private global::EpicChainAPI.v2.Container.Container container_;
        /// <summary>
        /// Container structure to register in NeoFS
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::EpicChainAPI.v2.Container.Container Container {
          get { return container_; }
          set {
            container_ = value;
          }
        }

        /// <summary>Field number for the "signature" field.</summary>
        public const int SignatureFieldNumber = 2;
        private global::EpicChainAPI.v2.Refs.Signature signature_;
        /// <summary>
        /// Signature of a stable-marshalled container according to RFC-6979
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::EpicChainAPI.v2.Refs.Signature Signature {
          get { return signature_; }
          set {
            signature_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Body);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Body other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Container, other.Container)) return false;
          if (!object.Equals(Signature, other.Signature)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (container_ != null) hash ^= Container.GetHashCode();
          if (signature_ != null) hash ^= Signature.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (container_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Container);
          }
          if (signature_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Signature);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (container_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Container);
          }
          if (signature_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Signature);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Body other) {
          if (other == null) {
            return;
          }
          if (other.container_ != null) {
            if (container_ == null) {
              Container = new global::EpicChainAPI.v2.Container.Container();
            }
            Container.MergeFrom(other.Container);
          }
          if (other.signature_ != null) {
            if (signature_ == null) {
              Signature = new global::EpicChainAPI.v2.Refs.Signature();
            }
            Signature.MergeFrom(other.Signature);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (container_ == null) {
                  Container = new global::EpicChainAPI.v2.Container.Container();
                }
                input.ReadMessage(Container);
                break;
              }
              case 18: {
                if (signature_ == null) {
                  Signature = new global::EpicChainAPI.v2.Refs.Signature();
                }
                input.ReadMessage(Signature);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  /// <summary>
  /// New NeoFS Container creation response
  /// </summary>
  public sealed partial class PutResponse : pb::IMessage<PutResponse> {
    private static readonly pb::MessageParser<PutResponse> _parser = new pb::MessageParser<PutResponse>(() => new PutResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EpicChainAPI.v2.Container.ServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutResponse(PutResponse other) : this() {
      body_ = other.body_ != null ? other.body_.Clone() : null;
      metaHeader_ = other.metaHeader_ != null ? other.metaHeader_.Clone() : null;
      verifyHeader_ = other.verifyHeader_ != null ? other.verifyHeader_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutResponse Clone() {
      return new PutResponse(this);
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 1;
    private global::EpicChainAPI.v2.Container.PutResponse.Types.Body body_;
    /// <summary>
    /// Body of container put response message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Container.PutResponse.Types.Body Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    /// <summary>Field number for the "meta_header" field.</summary>
    public const int MetaHeaderFieldNumber = 2;
    private global::EpicChainAPI.v2.Session.ResponseMetaHeader metaHeader_;
    /// <summary>
    /// Carries response meta information. Header data is used only to regulate
    /// message transport and does not affect request execution.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.ResponseMetaHeader MetaHeader {
      get { return metaHeader_; }
      set {
        metaHeader_ = value;
      }
    }

    /// <summary>Field number for the "verify_header" field.</summary>
    public const int VerifyHeaderFieldNumber = 3;
    private global::EpicChainAPI.v2.Session.ResponseVerificationHeader verifyHeader_;
    /// <summary>
    /// Carries response verification information. This header is used to
    /// authenticate the nodes of the message route and check the correctness of
    /// transmission.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.ResponseVerificationHeader VerifyHeader {
      get { return verifyHeader_; }
      set {
        verifyHeader_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Body, other.Body)) return false;
      if (!object.Equals(MetaHeader, other.MetaHeader)) return false;
      if (!object.Equals(VerifyHeader, other.VerifyHeader)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (body_ != null) hash ^= Body.GetHashCode();
      if (metaHeader_ != null) hash ^= MetaHeader.GetHashCode();
      if (verifyHeader_ != null) hash ^= VerifyHeader.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (body_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Body);
      }
      if (metaHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MetaHeader);
      }
      if (verifyHeader_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VerifyHeader);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (metaHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MetaHeader);
      }
      if (verifyHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VerifyHeader);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutResponse other) {
      if (other == null) {
        return;
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::EpicChainAPI.v2.Container.PutResponse.Types.Body();
        }
        Body.MergeFrom(other.Body);
      }
      if (other.metaHeader_ != null) {
        if (metaHeader_ == null) {
          MetaHeader = new global::EpicChainAPI.v2.Session.ResponseMetaHeader();
        }
        MetaHeader.MergeFrom(other.MetaHeader);
      }
      if (other.verifyHeader_ != null) {
        if (verifyHeader_ == null) {
          VerifyHeader = new global::EpicChainAPI.v2.Session.ResponseVerificationHeader();
        }
        VerifyHeader.MergeFrom(other.VerifyHeader);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (body_ == null) {
              Body = new global::EpicChainAPI.v2.Container.PutResponse.Types.Body();
            }
            input.ReadMessage(Body);
            break;
          }
          case 18: {
            if (metaHeader_ == null) {
              MetaHeader = new global::EpicChainAPI.v2.Session.ResponseMetaHeader();
            }
            input.ReadMessage(MetaHeader);
            break;
          }
          case 26: {
            if (verifyHeader_ == null) {
              VerifyHeader = new global::EpicChainAPI.v2.Session.ResponseVerificationHeader();
            }
            input.ReadMessage(VerifyHeader);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PutResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Container put response body contains information about the newly registered
      /// container as seen by `Container` smart contract. `ContainerID` can be
      /// calculated beforehand from the container structure and compared to the one
      /// returned here to make sure everything was done as expected.
      /// </summary>
      public sealed partial class Body : pb::IMessage<Body> {
        private static readonly pb::MessageParser<Body> _parser = new pb::MessageParser<Body>(() => new Body());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Body> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::EpicChainAPI.v2.Container.PutResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body(Body other) : this() {
          containerId_ = other.containerId_ != null ? other.containerId_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body Clone() {
          return new Body(this);
        }

        /// <summary>Field number for the "container_id" field.</summary>
        public const int ContainerIdFieldNumber = 1;
        private global::EpicChainAPI.v2.Refs.ContainerID containerId_;
        /// <summary>
        /// Unique identifier of the newly created container
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::EpicChainAPI.v2.Refs.ContainerID ContainerId {
          get { return containerId_; }
          set {
            containerId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Body);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Body other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(ContainerId, other.ContainerId)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (containerId_ != null) hash ^= ContainerId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (containerId_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(ContainerId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (containerId_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContainerId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Body other) {
          if (other == null) {
            return;
          }
          if (other.containerId_ != null) {
            if (containerId_ == null) {
              ContainerId = new global::EpicChainAPI.v2.Refs.ContainerID();
            }
            ContainerId.MergeFrom(other.ContainerId);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (containerId_ == null) {
                  ContainerId = new global::EpicChainAPI.v2.Refs.ContainerID();
                }
                input.ReadMessage(ContainerId);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  /// <summary>
  /// Container removal request
  /// </summary>
  public sealed partial class DeleteRequest : pb::IMessage<DeleteRequest> {
    private static readonly pb::MessageParser<DeleteRequest> _parser = new pb::MessageParser<DeleteRequest>(() => new DeleteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EpicChainAPI.v2.Container.ServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteRequest(DeleteRequest other) : this() {
      body_ = other.body_ != null ? other.body_.Clone() : null;
      metaHeader_ = other.metaHeader_ != null ? other.metaHeader_.Clone() : null;
      verifyHeader_ = other.verifyHeader_ != null ? other.verifyHeader_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteRequest Clone() {
      return new DeleteRequest(this);
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 1;
    private global::EpicChainAPI.v2.Container.DeleteRequest.Types.Body body_;
    /// <summary>
    /// Body of container delete request message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Container.DeleteRequest.Types.Body Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    /// <summary>Field number for the "meta_header" field.</summary>
    public const int MetaHeaderFieldNumber = 2;
    private global::EpicChainAPI.v2.Session.RequestMetaHeader metaHeader_;
    /// <summary>
    /// Carries request meta information. Header data is used only to regulate
    /// message transport and does not affect request execution.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.RequestMetaHeader MetaHeader {
      get { return metaHeader_; }
      set {
        metaHeader_ = value;
      }
    }

    /// <summary>Field number for the "verify_header" field.</summary>
    public const int VerifyHeaderFieldNumber = 3;
    private global::EpicChainAPI.v2.Session.RequestVerificationHeader verifyHeader_;
    /// <summary>
    /// Carries request verification information. This header is used to
    /// authenticate the nodes of the message route and check the correctness of
    /// transmission.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.RequestVerificationHeader VerifyHeader {
      get { return verifyHeader_; }
      set {
        verifyHeader_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Body, other.Body)) return false;
      if (!object.Equals(MetaHeader, other.MetaHeader)) return false;
      if (!object.Equals(VerifyHeader, other.VerifyHeader)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (body_ != null) hash ^= Body.GetHashCode();
      if (metaHeader_ != null) hash ^= MetaHeader.GetHashCode();
      if (verifyHeader_ != null) hash ^= VerifyHeader.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (body_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Body);
      }
      if (metaHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MetaHeader);
      }
      if (verifyHeader_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VerifyHeader);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (metaHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MetaHeader);
      }
      if (verifyHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VerifyHeader);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteRequest other) {
      if (other == null) {
        return;
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::EpicChainAPI.v2.Container.DeleteRequest.Types.Body();
        }
        Body.MergeFrom(other.Body);
      }
      if (other.metaHeader_ != null) {
        if (metaHeader_ == null) {
          MetaHeader = new global::EpicChainAPI.v2.Session.RequestMetaHeader();
        }
        MetaHeader.MergeFrom(other.MetaHeader);
      }
      if (other.verifyHeader_ != null) {
        if (verifyHeader_ == null) {
          VerifyHeader = new global::EpicChainAPI.v2.Session.RequestVerificationHeader();
        }
        VerifyHeader.MergeFrom(other.VerifyHeader);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (body_ == null) {
              Body = new global::EpicChainAPI.v2.Container.DeleteRequest.Types.Body();
            }
            input.ReadMessage(Body);
            break;
          }
          case 18: {
            if (metaHeader_ == null) {
              MetaHeader = new global::EpicChainAPI.v2.Session.RequestMetaHeader();
            }
            input.ReadMessage(MetaHeader);
            break;
          }
          case 26: {
            if (verifyHeader_ == null) {
              VerifyHeader = new global::EpicChainAPI.v2.Session.RequestVerificationHeader();
            }
            input.ReadMessage(VerifyHeader);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the DeleteRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Container removal request body has a signed `ContainerID` as a proof of
      /// container owner's intent. The signature will be verified by `Container`
      /// smart contract, so signing algorithm must be supported by NeoVM.
      /// </summary>
      public sealed partial class Body : pb::IMessage<Body> {
        private static readonly pb::MessageParser<Body> _parser = new pb::MessageParser<Body>(() => new Body());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Body> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::EpicChainAPI.v2.Container.DeleteRequest.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body(Body other) : this() {
          containerId_ = other.containerId_ != null ? other.containerId_.Clone() : null;
          signature_ = other.signature_ != null ? other.signature_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Body Clone() {
          return new Body(this);
        }

        /// <summary>Field number for the "container_id" field.</summary>
        public const int ContainerIdFieldNumber = 1;
        private global::EpicChainAPI.v2.Refs.ContainerID containerId_;
        /// <summary>
        /// Identifier of the container to delete from NeoFS
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::EpicChainAPI.v2.Refs.ContainerID ContainerId {
          get { return containerId_; }
          set {
            containerId_ = value;
          }
        }

        /// <summary>Field number for the "signature" field.</summary>
        public const int SignatureFieldNumber = 2;
        private global::EpicChainAPI.v2.Refs.Signature signature_;
        /// <summary>
        /// `ContainerID` signed with the container owner's key according to RFC-6979
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::EpicChainAPI.v2.Refs.Signature Signature {
          get { return signature_; }
          set {
            signature_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Body);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Body other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(ContainerId, other.ContainerId)) return false;
          if (!object.Equals(Signature, other.Signature)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (containerId_ != null) hash ^= ContainerId.GetHashCode();
          if (signature_ != null) hash ^= Signature.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (containerId_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(ContainerId);
          }
          if (signature_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Signature);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (containerId_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContainerId);
          }
          if (signature_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Signature);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Body other) {
          if (other == null) {
            return;
          }
          if (other.containerId_ != null) {
            if (containerId_ == null) {
              ContainerId = new global::EpicChainAPI.v2.Refs.ContainerID();
            }
            ContainerId.MergeFrom(other.ContainerId);
          }
          if (other.signature_ != null) {
            if (signature_ == null) {
              Signature = new global::EpicChainAPI.v2.Refs.Signature();
            }
            Signature.MergeFrom(other.Signature);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (containerId_ == null) {
                  ContainerId = new global::EpicChainAPI.v2.Refs.ContainerID();
                }
                input.ReadMessage(ContainerId);
                break;
              }
              case 18: {
                if (signature_ == null) {
                  Signature = new global::EpicChainAPI.v2.Refs.Signature();
                }
                input.ReadMessage(Signature);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  /// <summary>
  /// `DeleteResponse` has an empty body because delete operation is asynchronous
  /// and done via consensus in Inner Ring nodes.
  /// </summary>
  public sealed partial class DeleteResponse : pb::IMessage<DeleteResponse> {
    private static readonly pb::MessageParser<DeleteResponse> _parser = new pb::MessageParser<DeleteResponse>(() => new DeleteResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EpicChainAPI.v2.Container.ServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteResponse(DeleteResponse other) : this() {
      body_ = other.body_ != null ? other.body_.Clone() : null;
      metaHeader_ = other.metaHeader_ != null ? other.metaHeader_.Clone() : null;
      verifyHeader_ = other.verifyHeader_ != null ? other.verifyHeader_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteResponse Clone() {
      return new DeleteResponse(this);
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 1;
    private global::EpicChainAPI.v2.Container.DeleteResponse.Types.Body body_;
    /// <summary>
    /// Body of container delete response message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Container.DeleteResponse.Types.Body Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    /// <summary>Field number for the "meta_header" field.</summary>
    public const int MetaHeaderFieldNumber = 2;
    private global::EpicChainAPI.v2.Session.ResponseMetaHeader metaHeader_;
    /// <summary>
    /// Carries response meta information. Header data is used only to regulate
    /// message transport and does not affect request execution.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.ResponseMetaHeader MetaHeader {
      get { return metaHeader_; }
      set {
        metaHeader_ = value;
      }
    }

    /// <summary>Field number for the "verify_header" field.</summary>
    public const int VerifyHeaderFieldNumber = 3;
    private global::EpicChainAPI.v2.Session.ResponseVerificationHeader verifyHeader_;
    /// <summary>
    /// Carries response verification information. This header is used to
    /// authenticate the nodes of the message route and check the correctness of
    /// transmission.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EpicChainAPI.v2.Session.ResponseVerificationHeader VerifyHeader {
      get { return verifyHeader_; }
      set {
        verifyHeader_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Body, other.Body)) return false;
      if (!object.Equals(MetaHeader, other.MetaHeader)) return false;
      if (!object.Equals(VerifyHeader, other.VerifyHeader)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (body_ != null) hash ^= Body.GetHashCode();
      if (metaHeader_ != null) hash ^= MetaHeader.GetHashCode();
      if (verifyHeader_ != null) hash ^= VerifyHeader.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (body_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Body);
      }
      if (metaHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MetaHeader);
      }
      if (verifyHeader_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(VerifyHeader);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (metaHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MetaHeader);
      }
      if (verifyHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VerifyHeader);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteResponse other) {
      if (other == null) {
        return;
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::